
package com.training.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentServiceImpl", targetNamespace = "http://ws.training.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentServiceImpl {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getStudentInfoReturn", targetNamespace = "http://ws.training.com")
    @RequestWrapper(localName = "getStudentInfo", targetNamespace = "http://ws.training.com", className = "com.training.ws.GetStudentInfo")
    @ResponseWrapper(localName = "getStudentInfoResponse", targetNamespace = "http://ws.training.com", className = "com.training.ws.GetStudentInfoResponse")
    public String getStudentInfo();

    /**
     * 
     * @param stud
     */
    @WebMethod
    @RequestWrapper(localName = "addStudent", targetNamespace = "http://ws.training.com", className = "com.training.ws.AddStudent")
    @ResponseWrapper(localName = "addStudentResponse", targetNamespace = "http://ws.training.com", className = "com.training.ws.AddStudentResponse")
    public void addStudent(
        @WebParam(name = "stud", targetNamespace = "http://ws.training.com")
        Student stud);

}
